[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
talent_olympics_marketplace_for_services = "C19PZG14VjxjmqGQqARnC3nvydYM8TcmydANZr3Zc8Uq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
